services:
  coe-cli:
    build: .
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COE_BACKEND_URL=http://coe-backend:8000 # Point to the backend service name
    stdin_open: true
    tty: true
    depends_on:
      - coe-backend # Ensure backend starts before cli

  coe-backend:
    build:
      context: /Users/mjkim/development/CoE-Backend # CoE-Backend 프로젝트의 실제 경로
      dockerfile: Dockerfile # CoE-Backend 프로젝트 내의 Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env # 이 .env 파일은 CoE-Backend 프로젝트 디렉토리에 있어야 합니다.
